#=================================================================================================#
#                                 Main Configuration of Chat Manager
#=================================================================================================#
#
#    If you need any plugin support, feel free to join our discord server
#    or private message me H1DD3NxN1NJA on Spigot.
#
#    Discord Link: https://discord.gg/n9A9xtA
#
#=================================================================================================#
#
# Information:
#   1. Color Codes are supported with the "&" character.
#      - To view a list of COLOR CODES you can do /Colors in-game.
#      - To view a list of FORMAT CODES you can do /Formats in-game.
#   
#   2. Sound List
#      - 1.9 and newer: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#      - 1.8 and older: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
#   
#   3. All messages are in the Messages.yml file
#
#=================================================================================================#
  
#=================================================================================================#
# Block players from advertising other servers.
#=================================================================================================#
Anti_Advertising:

  Enable: true
  
  #Should the anti advertising checker be more sensitive?
  #WARNING! May cause a lot of false positives!
  Increase_Sensitivity: false

  #Should staff get notified when a player advertises in chat or commands?
  Notify_Staff: true
  
  #Should a command be executed to the player that advertises?
  Execute_Command: false

  #The command that is executed when a player advertises.
  #Set this section to Executed_Command: '' to disable
  Executed_Command: kick {player} Please do not advertise in chat

  #Every time a player advertises in chat, their message will be logged in the Advertisements.txt file.
  Log_Advertisers: true

  #IP-Addresses that can be used in chat. CASE SENSITIVE!
  Whitelist:
  - "Google.com"

#=================================================================================================#
# Prevent players from executing commands, 
# or typing in chat until they move when they join your server.
#=================================================================================================#
Anti_Bot:

  #Block players from typing in chat until they move.
  Block_Chat_Until_Moved: true

  #Block players from executing commands until they move.
  Block_Commands_Until_Moved: true

#=================================================================================================#
# Prevent messages written in CAPS.
#=================================================================================================#
Anti_Caps:

  Enable: true

  #Should players capitalize words in commands?
  Enable_In_Commands: true

  #The minimum size the message has to be to get blocked.
  Min_Message_Length: 5

  #The percentage the message has to be capitalized to get blocked.
  Required_Percentage: 70

#=================================================================================================#
# Prevent the chat from being flooded with repetitive messages.
#=================================================================================================#
Anti_Spam:

  #Anti-spam section for chat.
  Chat:

    #How many seconds does the player have to wait till they send their next message?
    #Set to 0 to disable.
    Chat_Delay: 5

    #Prevent players from repeating the same messages.
    Block_Repetitive_Messages: true

  #Anti-spam section for commands.
  Command:

    #How many seconds does the player have to wait till they send their next command?
    #Set to 0 to disable.
    Command_Delay: 5

    #Prevent players from repeating the same commands.
    Block_Repetitive_Commands: true

#=================================================================================================#
# Prevent players from swearing in chat.
#=================================================================================================#
Anti_Swear:

  Enable: true
  
  #Should the anti-swear checker be more sensitive?
  #WARNING! May cause a lot of false positives!
  Increase_Sensitivity: false

  #Should staff get notified when a player swears in chat or commands?
  Notify_Staff: true

  #Should a command be executed to the player that swears?
  Execute_Command: true

  #The command that is executed when a player swears.
  #Set this section to Executed_Command: '' to disable
  Executed_Command: kick {player} Please do not swear in chat
  
  #Block swearing in commands.
  Block_Commands: true
  
  #If a player executes one of these commands with a swear word in it, the command will not be blocked.
  Whitelisted_Commands:
  - "/report"
  - "/login"
  - "/register"

  #Every time a player swears in chat, their message will be logged in the Swears.txt file.
  Log_Swearing: true

#=================================================================================================#
# Prevent players from using certain commands.
#=================================================================================================#
Banned_Commands:

  Enable: true

  #Should staff get notified when a player uses a banned command?
  Notify_Staff: true

  #Should a command be executed to the player that uses a banned command?
  Execute_Command: true

  #The command that is executed when a player executed a banned command.
  #Set this section to Executed_Command: '' to disable
  Executed_Command: kick {player} You are not allowed to use that command!

#=================================================================================================#
# Broadcast Commands
#=================================================================================================#
Broadcast_Commands:

  Command:
    
    #/Bradcast Command
    Broadcast:
    
      #The default prefix that goes infront of the broadcasted message.
      Prefix: "&c[&4Broadcast&c]&r "
      
      #The default color the broadcasted message will be.
      Default_Color: "&b"
      
      #The sound that will be sent to everyone on the server when a broadcasted message is sent.
      #Set to '' to disable
      Sound: ''
      
    #/Announce Command
    Announcement:
    
      #The sound that will be sent to everyone on the server when an announcement is sent.
      #Set to '' to disable
      Sound: ''
      
      #The message that will be sent to everyone on the server.
      Message:
        - "&8------------------------------"
        - "           &7. . .&6&lANNOUNCEMENT&7. . .   "
        - "&8------------------------------"
        - "{message}"
        - "&8------------------------------"
        
    #/Warning Command
    Warning:
    
      #The sound that will be sent to everyone on the server when a warning message is sent.
      #Set to '' to disable
      Sound: ''
      
      #The message that will be sent to everyone on the server.
      Message:
        - "&8------------------------------"
        - "           &7. . .&4&lWARNING&7. . .   "
        - "&8------------------------------"
        - "{message}"
        - "&8------------------------------"
        
#=================================================================================================#
# Per-Group chat formats. REQUIRES VAULT TO WORK!!!!!
#=================================================================================================#
Chat_Format:

  Enable: true

  #This will only be used if the players permission group isn't on the bottom of this section.
  Default_Format: "&8[&7Default&8] &7{player} &9> &7{message}"

  #Chat Formats are set depending on what permission group the player is in.
  #If a player is in the permission group named "Default" they will have the default chat format.
  Groups:
    Default: 
      Format: "&8[&7Default&8] &7{player} &9> &7{message}"
    VIP: 
      Format: "&8[&5VIP&8] &7{displayname} &9> &7{message}"
    Moderator: 
      Format: "&b[&6Moderator&b] &a[&b{world}&a] &b{player} &9> &e{message}"
      
#=================================================================================================#
# Players can only send messages to other players that are in range.
#=================================================================================================#
Chat_Radius:

  Enable: false
  
  #The maximum distance players will receive the senders messages.
  Block_Distance: 250

#=================================================================================================#
# Clear Chat
#=================================================================================================#
Clear_Chat:

  #Should the clear chat message be broadcasted to everyone on the server?
  Broadcast: true

  #Should staff get notified when chat is cleared?
  Notify_Staff: false

  #How many blank lines should be broadcasted in chat?
  Broadcasted_Lines: 300

#=================================================================================================#
# Correct player's grammar.
#=================================================================================================#
Grammar:

  Enable: true
  
  #The minimum size the players message has to be for grammar to work.
  Min_Message_Length: 5

  #Correct words from "i" to "I", "dont" to "don't", and many more pre-set words!
  Autocorrect:
    Enable: true

#=================================================================================================#
# Logs
#=================================================================================================#
Logs:

  #Should every message in chat be logged in the Chat.txt file?
  Log_Chat: true

  #Should every command that is executed be logged in the Commands.txt file?
  Log_Commands: true
  
  #Commands that wont be logged in the Command.txt file.
  #Commands in the Blacklist_Commands list must be lowercase.
  Blacklist_Commands:
  - "/login"
  - "/register"

#=================================================================================================#
# First Join, Join, and Quit Messages.
#=================================================================================================#
Messages:

  Enable: true

  First_Join_Message: "&eWelcome &b{player} &eto the server!"

  Join: "&b{player} &ejoined the server."

  Quit: "&b{player} &eleft the server."

#=================================================================================================#
# When players join your server, welcome them with a Message of the Day.
#=================================================================================================#
MOTD:

  Enable: true

  #How long to wait before displaying after login in seconds?
  Delay: 2

  Message:
  - "&d&m------------------------------------"
  - "&eWelcome to the server &d{player}!"
  - "&eHope you enjoy your stay!"
  - ""
  - "&eYou can change this message in the ChatManager - Config.yml"
  - "&d&m------------------------------------"

#=================================================================================================#
# Mute Chat.
#=================================================================================================#
Mute_Chat:

  #Should mute chat messages be broadcasted to everyone on the server?
  Broadcast: true

  #Should staff get notified when chat is muted?
  Notify_Staff: false

  #Hide the following messages while chat is muted.
  Silence:
    First_Join_Message: false
    Join_Message: false
    Quit_Message: false

  Disable_Commands: true

  #Commands that cannot be executed when chat is muted 
  #if the boolean "Disable_Commands" is set to true.
  Disabled_Commands:
  - message
  - msg
  - m
  - tell
  - t
  - whisper
  - w
  - me
  - reply
  - r

#=================================================================================================#
# Players can only talk to other players that are in the same world as them!
#=================================================================================================#
Per_World_Chat:

  Enable: false

#=================================================================================================#
# Private messages allow you to secretly message another player without everyone else seeing.
#=================================================================================================#
Private_Messages:

  Format_Sender: "&c&l(!) &f&l[&e&lYou &d-> &e{receiver}&f&l] &b"

  Format_Receiver: "&c&l(!) &f&l[&e{player} &d-> &e&lYou&f&l] &b"

  #The sound thats played to the receiver
  #Do Sound: '' to disable
  Sound: ''

#=================================================================================================#
# Server Rules.
#=================================================================================================#
Rules:

  Enable: true
  
#=================================================================================================#
# Staff can see what players type in certain commands.
#=================================================================================================#
Social_Spy:

  #These commands will be monitored when socialspy is enabled.
  Command_List:
  - /message
  - /msg
  - /m
  - /whisper
  - /w
  - /tell
  - /t
  - /reply
  - /r

#=================================================================================================#
# Talk silently with staff without everyone else on the server seeing.
#=================================================================================================#
Staff_Chat:

  Enable: true

  Format: "&e[&bStaff-Chat&e] &a{player} &7> &b{message}"
  
#=================================================================================================#
# Checks if there is an available update for chat manager.
#=================================================================================================#
Update_Checker: true

#=================================================================================================#
# You are done with the config!
#=================================================================================================#
