name: ChatManager
description: Chat management plugin
version: ${project.version}
main: me.H1DD3NxN1NJA.ChatManager.Main
author: H1DD3NxN1NJA
softdepend: [PlaceholderAPI, Vault, Essentials, SuperVanish, DeluxeTags, Factions]
api-version: 1.13

permissions:
    chatmanager.bypass.all:
        description: Give players access to bypass every check.
        default: false
        children:
            chatmanager.bypass.antiadvertising: true
            chatmanager.bypass.antibot: true
            chatmanager.bypass.antiswear: true
            chatmanager.bypass.bannedcommands: true
            chatmanager.bypass.caps: true
            chatmanager.bypass.chatdelay: true
            chatmanager.bypass.chatradius: true
            chatmanager.bypass.clearchat: true
            chatmanager.bypass.commanddelay: true
            chatmanager.bypass.commandspy: true
            chatmanager.bypass.dupe.chat: true
            chatmanager.bypass.dupe.command: true
            chatmanager.bypass.grammar: true
            chatmanager.bypass.mutechat: true
            chatmanager.bypass.socialspy: true
    chatmanager.formats.all:
        description: Give players access to use all color and format codes in chat and on signs.
        default: false
        children:
            chatManager.format.color: true
            chatManager.format.magic: true
            chatManager.format.bold: true
            chatManager.format.strikethrough: true
            chatManager.format.underline: true
            chatManager.format.italic: true
            chatManager.sign.color: true
            chatManager.sign.format: true
    chatmanager.commands.all:
        description: Give players access to every command.
        default: false
        children:
            chatmanager.antiSwear.add: true
            chatmanager.antiSwear.list: true
            chatmanager.antiSwear.remove: true
            chatmanager.autobroadcast: true
            chatmanager.autobroadcast.add: true
            chatmanager.autobroadcast.create: true
            chatmanager.autobroadcast.list: true
            chatmanager.bannedCommands.add: true
            chatmanager.bannedCommands.list: true
            chatmanager.bannedCommands.remove: true
            chatmanager.announcement: true
            chatmanager.broadcast: true
            chatmanager.clearchat: true
            chatmanager.commandcpy: true
            chatmanager.mutechat: true
            chatmanager.perworldchat: true
            chatmanager.ping: true
            chatmanager.ping.others: true
            chatmanager.preview.title: true
            chatmanager.preview.actionbar: true
            chatmanager.privatemessage: true
            chatmanager.reload: true
            chatmanager.rules: true
            cbatmanager.socialspy: true
            chatmanager.staffchat: true
            chatmanager.warning: true
    chatmanager.notify.all:
        description: Gets notified everytime a player breaks the rules.
        default: false
        children:
            chatmanager.notify.antiadvertising: true
            chatmanager.notify.antiswear: true
            chatmanager.notify.bannedcommands: true
    chatmanager.*:
        description: Give players with op everything by default.
        default: op
        children:
            chatmanager.bypass.all: true
            chatmanager.commands.all: true
            chatmanager.notify.all: true
            chatmanager.formats.all: true
