#=================================================================================================#
#                                 Main Configuration of Chat Manager
#=================================================================================================#
#
#    If you need any plugin support, feel free to join our discord server
#    or private message me H1DD3NxN1NJA on Spigot.
#
#    Discord Link: https://discord.gg/n9A9xtA
#
#=================================================================================================#
#
# Information:
#   1. Color Codes are supported with the "&" character.
#      - To view a list of COLOR CODES you can do /Colors in-game.
#      - To view a list of FORMAT CODES you can do /Formats in-game.
#   
#   2. Sound List
#      - 1.9 and newer: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#      - 1.8 and older: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
#   
#   3. All messages are in the Messages.yml file.
#
#=================================================================================================#
  
#=================================================================================================#
# Block players from advertising other servers.
#=================================================================================================#
Anti_Advertising:

  Chat:
    
    #Block advertising in chat.
    Enable: true
  
    #Should the anti advertising checker be more sensitive? This may cause false positives.
    Increase_Sensitivity: false

    #Should staff get notified when a player advertises in chat?
    Notify_Staff: true
  
    #Should a command be executed to the player that advertises?
    Execute_Command: false

    #The command that is executed when a player advertises.
    #Set this section to Executed_Command: '' to disable
    Executed_Command: kick {player} Please do not advertise in chat

    #Every time a player advertises in chat, their message will be logged in the Advertisements.txt file.
    Log_Advertisers: true
    
  Commands:
  
    #Block advertising in commands.
    Enable: true
  
    #Should the anti advertising checker be more sensitive? This may cause false positives.
    Increase_Sensitivity: false

    #Should staff get notified when a player advertises in commands?
    Notify_Staff: true
  
    #Should a command be executed to the player that advertises?
    Execute_Command: false

    #The command that is executed when a player advertises.
    #Set this section to Executed_Command: '' to disable
    Executed_Command: kick {player} Please do not advertise in chat

    #Every time a player advertises in commands, their message will be logged in the Advertisements.txt file.
    Log_Advertisers: true
    
  Signs:
  
    #Block advertising on signs. 
    Enable: true
  
    #Should the anti advertising checker be more sensitive? This may cause false positives.
    Increase_Sensitivity: false

    #Should staff get notified when a player advertises on a sign?
    Notify_Staff: true
  
    #Should a command be executed to the player that advertises?
    Execute_Command: false

    #The command that is executed when a player advertises.
    #Set this section to Executed_Command: '' to disable
    Executed_Command: kick {player} Please do not advertise in chat

    #Every time a player advertises on signs, their message will be logged in the Advertisements.txt file.
    Log_Advertisers: true

  #Websites that wont be blocked if said in chat, commands, or signs.
  Whitelist:
  - "google.com"

#=================================================================================================#
# Prevent players from executing commands, or typing in chat until they move when they join your server.
#=================================================================================================#
Anti_Bot:

  #Block players from typing in chat until they move.
  Block_Chat_Until_Moved: true

  #Block players from executing commands until they move.
  Block_Commands_Until_Moved: true

#=================================================================================================#
# Prevent messages written in CAPS.
#=================================================================================================#
Anti_Caps:

  Enable: true

  #Should players capitalize words in commands?
  Enable_In_Commands: true

  #The minimum size the message has to be to get blocked.
  Min_Message_Length: 5

  #The percentage the message has to be capitalized to get blocked.
  Required_Percentage: 70

#=================================================================================================#
# Prevent the chat from being flooded with repetitive messages.
#=================================================================================================#
Anti_Spam:

  #Anti-spam section for chat.
  Chat:

    #How many seconds does the player have to wait till they send their next message?
    #Set to 0 to disable.
    Chat_Delay: 5

    #Prevent players from repeating the same messages.
    Block_Repetitive_Messages: true

  #Anti-spam section for commands.
  Command:

    #How many seconds does the player have to wait till they send their next command?
    #Set to 0 to disable.
    Command_Delay: 5

    #Prevent players from repeating the same commands.
    Block_Repetitive_Commands: true

#=================================================================================================#
# Prevent players from swearing in chat, comamnds, and signs.
#=================================================================================================#
Anti_Swear:

  Chat:
    
    #Block swearing in chat
    Enable: true
  
    #Should the anti-swear checker be more sensitive? This may cause false positives.
    Increase_Sensitivity: false
    
    #Should staff get notified when a player swears in chat?
    Notify_Staff: true
    
    #Should a command be executed when a player swears in chat?
    Execute_Command: true

    #The command that is executed when a player swears in chat.
    #Set this section to Executed_Command: '' to disable.
    Executed_Command: kick {player} Please do not swear in chat
    
    #Every time a player swears in chat their message will be logged in the Swears.txt file.
    Log_Swearing: true
  
  Commands:
  
    #Block swearing in commands.
    Enable: true
    
    #Should the anti-swear checker be more sensitive? This may cause false positives.
    Increase_Sensitivity: false
  
    #If a player executes one of these commands with a swear word in it, the command will not be blocked.
    Whitelisted_Commands:
    - "/report"
    - "/login"
    - "/register"
    
    #Should staff get notified when a player swears in commands?
    Notify_Staff: true
    
    #Should a command be executed when a player swears in commands?
    Execute_Command: true

    #The command that is executed when a player swears in commands.
    #Set this section to Executed_Command: '' to disable.
    Executed_Command: kick {player} Please do not swear in commands
    
    #Every time a player swears in commands their message will be logged in the Swears.txt file.
    Log_Swearing: true
    
  Signs:
  
    #Block swearing on signs.
    Enable: true
    
    #Should the anti-swear checker be more sensitive? This may cause false positives.
    Increase_Sensitivity: false
  
    #Should staff get notified when a player swears on signs?
    Notify_Staff: true

    #Should a command be executed when a player swears on signs?
    Execute_Command: true

    #The command that is executed when a player swears on signs.
    #Set this section to Executed_Command: '' to disable
    Executed_Command: kick {player} Please do not swear on signs
    
    #Every time a player swears on signs their message will be logged in the Swears.txt file.
    Log_Swearing: true
    
#=================================================================================================#
# Prevent players from using special chat characters.
#=================================================================================================#
Anti_Unicode:
  
  #Block special characters in chat.
  Enable: true
    
  #Should staff get notified when a player uses special characters in chat?
  Notify_Staff: true
    
  #Should a command be executed when a player uses special characters in chat?
  Execute_Command: false

  #The command that is executed when a player uses special characters in chat.
  #Set this section to Executed_Command: '' to disable
  Executed_Command: kick {player} Please do not use special characters in chat.

#=================================================================================================#
# Prevent players from using certain commands.
#=================================================================================================#
Banned_Commands:

  Enable: true

  #Should staff get notified when a player uses a banned command?
  Notify_Staff: true

  #Should a command be executed to the player that uses a banned command?
  Execute_Command: true

  #The command that is executed when a player executed a banned command.
  #Set this section to Executed_Command: '' to disable
  Executed_Command: kick {player} You are not allowed to use that command!

#=================================================================================================#
# Broadcast Commands
#=================================================================================================#
Broadcast_Commands:

  Command:
    
    #/Bradcast Command
    Broadcast:
    
      #The default prefix that goes infront of the broadcasted message.
      Prefix: "&c[&4Broadcast&c]&r "
      
      #The default color the broadcasted message will be.
      Default_Color: "&b"
      
      #The sound that will be sent to everyone on the server when a broadcasted message is sent.
      #Set to '' to disable
      Sound: ''
      
    #/Announce Command
    Announcement:
    
      #The sound that will be sent to everyone on the server when an announcement is sent.
      #Set to '' to disable
      Sound: ''
      
      #The message that will be sent to everyone on the server.
      Message:
        - "&8------------------------------"
        - "           &7. . .&6&lANNOUNCEMENT&7. . .   "
        - "&8------------------------------"
        - "{message}"
        - "&8------------------------------"
        
    #/Warning Command
    Warning:
    
      #The sound that will be sent to everyone on the server when a warning message is sent.
      #Set to '' to disable
      Sound: ''
      
      #The message that will be sent to everyone on the server.
      Message:
        - "&8------------------------------"
        - "           &7. . .&4&lWARNING&7. . .   "
        - "&8------------------------------"
        - "{message}"
        - "&8------------------------------"
        
#=================================================================================================#
# Per-Group chat formats. REQUIRES VAULT TO WORK!!!!!
# Available Placeholders:
#   - {message} - Shows the players message.
#   - {player} - Shows the players name.
#   - {displayname} - Shows the players displayname.
#   - {world} - Shows the world the player is currently in.
#   - {vault_prefix} - Shows the players prefix.
#   - {vault_suffix} - Shows the players suffix.
#   - {vault_rank} - Shows the players rank.
#   - {ess_player_balance} - Shows the players balance.
#   - {ess_player_nickname} - Shows the players nickname.
#   - {factions_faction} - Shows the players faction name.
#   - {factions_role_prefix} - Shows the players role (-|+|*|**).
#   - {factions_role_name} - Shows the players role name (Member, Officer, Leader).
#   - {factions_player_power} - Shows the players current power level.
#   - {factions_player_max_power} - Shows the players max power level.
#   - {factions_faction_power} - Show the factions current power level.
#   - {factions_faction_max_power} - Shows the factions max power level.
#   - You can use PlaceholderAPI for more placeholders.
#=================================================================================================#
Chat_Format:

  Enable: true

  #This will only be used if the players permission group isn't on the bottom of this section.
  Default_Format: "&8[&7Default&8] &7{player} &9> &7{message}"

  #Chat Formats are set depending on what permission group the player is in.
  #If a player is in the permission group named "Default" they will have the default chat format.
  Groups:
    Default:
      Format: "&8[&7Default&8] &7{player} &9> &7{message}"
    VIP:
      Format: "&8[&5VIP&8] &7{displayname} &9> &7{message}"
    Moderator:
      Format: "&a[&3Moderator&a] &b{player} &9> &e{message}"
    Owner:
      Format: "&b[&6Owner&b] {player} &9>> &e{message}"
      
#=================================================================================================#
# Players can only send messages to other players that are in range.
#=================================================================================================#
Chat_Radius:

  Enable: false
  
  #The maximum distance players will receive the senders messages.
  Block_Distance: 250

#=================================================================================================#
# Clear Chat
#=================================================================================================#
Clear_Chat:

  #Should the clear chat message be broadcasted to everyone on the server?
  Broadcast: true

  #Should staff get notified when chat is cleared?
  Notify_Staff: false

  #How many blank lines should be broadcasted in chat?
  Broadcasted_Lines: 300

#=================================================================================================#
# Correct player's grammar.
#=================================================================================================#
Grammar:

  Enable: true
  
  #The minimum size the players message has to be for grammar to work.
  Min_Message_Length: 5

  #Correct words from "i" to "I", "dont" to "don't", and many more pre-set words!
  Autocorrect:
    Enable: true

#=================================================================================================#
# Logs
#=================================================================================================#
Logs:

  #Should every message in chat be logged in the Chat.txt file?
  Log_Chat: true

  #Should every command that is executed be logged in the Commands.txt file?
  Log_Commands: true
  
  #Should every message placed on a sign be logged in the Signs.txt file?
  Log_Signs: true
  
  #Commands that wont be logged in the Command.txt file.
  #Commands in the Blacklist_Commands list must be lowercase.
  Blacklist_Commands:
  - "/login"
  - "/register"

#=================================================================================================#
# First Join, Join, and Quit Messages.
#=================================================================================================#
Messages:

  Enable: true

  First_Join_Message: "&eWelcome &b{player} &eto the server!"

  Join_Message: "&b{player} &ejoined the server."

  Quit_Message: "&b{player} &eleft the server."

Actionbar_Messages:

  Enable: true
  
  First_Join_Message: "&eWelcome &b{player} &eto {server_name}!"

  Join_Message: "&eWelcome back &b{player}!"

Title_Messages:

  Enable: true
  
  First_Join_Title:
    Header: "&eWelcome"
    Footer: "&b{player} to {server_name}"
    
  Join_Title:
    Header: "&eWelcome Back"
    Footer: "&b{player} to {server_name}"

#=================================================================================================#
# When players join your server, welcome them with a Message of the Day.
#=================================================================================================#
MOTD:

  Enable: true

  #How long to wait before displaying after login in seconds?
  Delay: 2

  Message:
  - "&7&m------------------------------------"
  - "&aWelcome to the server &b{player}&a!"
  - ""
  - "&aIf you need any help please message any online staff member."
  - ""
  - "&aYou can change this message in the ChatManager - Config.yml"
  - "&7&m------------------------------------"

#=================================================================================================#
# Mute Chat.
#=================================================================================================#
Mute_Chat:

  #Should mute chat messages be broadcasted to everyone on the server?
  Broadcast: true

  #Should staff get notified when chat is muted?
  Notify_Staff: false

  Disable_Commands: true

  #Commands that cannot be executed when chat is muted 
  #if the boolean "Disable_Commands" is set to true.
  Disabled_Commands:
  - "/message"
  - "/msg"
  - "/m"
  - "/tell"
  - "/t"
  - "/whisper"
  - "/w"
  - "/me"
  - "/reply"
  - "/r"

#=================================================================================================#
# Players can only talk to other players that are in the same world as them!
#=================================================================================================#
Per_World_Chat:

  Enable: false

#=================================================================================================#
# Private messages allow you to secretly message another player without everyone else seeing.
#=================================================================================================#
Private_Messages:

  Format_Sender: "&c&l(!) &f&l[&e&lYou &d-> &e{receiver}&f&l] &b"

  Format_Receiver: "&c&l(!) &f&l[&e{player} &d-> &e&lYou&f&l] &b"

  #The sound thats played to the receiver
  #Do Sound: '' to disable
  Sound: ''

#=================================================================================================#
# Server Rules.
#=================================================================================================#
Rules:

  Enable: true

#=================================================================================================#
# The server name used in {server_name} variable. Color codes are supported.
#=================================================================================================#
Server_Name: "Server Name"
  
#=================================================================================================#
# Staff can see what players type in certain commands.
#=================================================================================================#
Social_Spy:

  #These commands will be monitored when social spy is enabled.
  Command_List:
  - "/message"
  - "/msg"
  - "/m"
  - "/whisper"
  - "/w"
  - "/tell"
  - "/t"
  - "/reply"
  - "/r"

#=================================================================================================#
# Talk silently with staff without everyone else on the server seeing.
#=================================================================================================#
Staff_Chat:

  Enable: true

  Format: "&e[&bStaff-Chat&e] &a{player} &7> &b{message}"
  
#=================================================================================================#
# Checks if there is an available update for chat manager.
#=================================================================================================#
Update_Checker: true

#=================================================================================================#
# You are done with the config!
#=================================================================================================#
